# fly.toml app configuration file generated for nub on 2023-11-19T06:44:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nub"
primary_region = "iad"

[build]

[http_service]
internal_port = 8080
force_https = false        # We force HTTPS via middleware so we can do a single redirect from eg http://www.nub.com to https://nub.com
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[mounts]
source = "litefs"
destination = "/app/.data"
