name: CI/CD
on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  APP: ${{ github.head_ref }}-nub

jobs:
  destroy-branch-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Remove branch preview
        run: flyctl apps destroy "$APP" -y || true
